### ISSUE TITLE
Great project, but I have a side question

### ISSUE THREAD

**Issue by mebillica** [PicoPlanetDev/Stratasys-Mojo-Conversion#1]
This project looks very interesting. I recently acquired a MOJO from work. I have a bunch of filament, but only 1 build plate. Do you happen to have the build plate in fusion360? I would like to print out more on my other printers. Thanks for any help, and keep up the good work with this!! 

Bill

**Comment by sigmondkukla** [comment]
Hi Bill!

Thanks for your interest in this project -- we actually had the opposite
problem, too many build plates and only a little filament left (the basis
for this project). I do have the build plate in Fusion and I'll send it to
you when I get a chance later today, however I don't think it has the
little locking tabs on the bottom. I'll try and add that to my design, but
I mainly had that design for the PrusaSlicer visualization only.
Here's what we do to conserve build plates though, as it may help you out.
Get some really wide blue painter's tape, or less expensive transfer tape,
and cover the build plate. Then, cut the excess off the edges and use a
plastic squeegee or scraper to flatten out air bubbles. Finally, use a glue
stick to make it sticky. In that way we get many uses out of the same build
plate by just re-covering it each time.

I'll update you on the file when I have a chance.

Best,
Sig

**Comment by sigmondkukla** [comment]
@mebillica Just uploaded the Fusion design file for it. However, this version is pretty much for aesthetics only and I don't guarantee it's entirely true to life. It also lacks those clips. I can work on it a little more later to try and get a usable printable version.
https://github.com/PicoPlanetDev/Stratasys-Mojo-Conversion/blob/main/cad/Fusion/Mojo%20Build%20Plate%20v5.f3d

**Comment by mebillica** [comment]
Thank you so much!! Wow, I'll be printing this tonight when I get home! Maybe I can figure out the tabs. Not the best in Fusion. I did see another video, where someone put down a little glue stick, all over the plate, then covered it completely with Kapton tape. This worked EXTREMELY well! So at least I have it protected.

**Comment by mebillica** [comment]
Am update for you. My Fusion360 skills are not the best, but I have the tabs added, and the little "lock" as well. I've printed this in ABS on my home Prusa MK4. They fit PERFECTLY onto the Mojo! Snaps/locks in perfect! I have printed on them. They work just like the original build plates. I have read the original plates are ABS as well, but I don't know. MY plates will melt/warp in the wash station. Stock plate does not. But I have found that Kapton/glue stick trick works AMAZINGLY well! When the print finishes, give a little twist to the plate, and the part pops off! Larger, 3x3 print, showed a minor corners lifting. So I'm thinking anything bigger than 3x3 will require a plate without the Kapton tape. But now that I can print plates at home, that doesn't matter. You saved me big time, as I only had the single plate! Would you mind if I uploaded the STL to thingiverse? Might help someone else in need. I'll attach the files here later from my PC for you. Thanks again!! 

Bill
![PXL_20240531_120102100](https://github.com/PicoPlanetDev/Stratasys-Mojo-Conversion/assets/76922210/b465e70d-a95a-4f1b-b292-6fbc5217bf70)
![PXL_20240531_120040199](https://github.com/PicoPlanetDev/Stratasys-Mojo-Conversion/assets/76922210/d967a78d-7df2-4221-8bc9-80e05a6c286d)
![PXL_20240530_151502834](https://github.com/PicoPlanetDev/Stratasys-Mojo-Conversion/assets/76922210/2ebf5b98-c479-44f1-bf28-680108eaf1d6)
![PXL_20240530_144658241](https://github.com/PicoPlanetDev/Stratasys-Mojo-Conversion/assets/76922210/25dc3ce3-a4fb-4798-8ccd-1f615f5f41c5)
![PXL_20240530_113115704](https://github.com/PicoPlanetDev/Stratasys-Mojo-Conversion/assets/76922210/cc299fd2-4108-451f-b110-6a1330dc8173)

**Comment by sigmondkukla** [comment]
These build plates look great! I'd love if you were able to upload the STL to Thingiverse, as I'm sure one day many labs like ours will run out. Whenever you get the chance to share the Fusion files as well, I'll update that in this repo / or make a pull request for it.

I'm glad the transfer tape solution has been working out, as it's really saved us for many prints. With regards to the warping, I have found that to be the case sometimes as well. Not sure if you can get around it too much but we do have discussions of whether we should "burn a plate" for a critical print or if we can just do it with the tape.

I've actually never put the build plates in the wash bath! We always use a long old flat head screwdriver to chip the raft off of the bottom, and clean off as much support as possible so we don't use up our wash bath chemical too fast. Maybe that'll help in the reuse of those plates. I wonder, if that solution does work out, if they could even be printed in PLA and not melt too badly as it prints.

All in all, your design looks great though and this is a huge contribution to the project and community (if there is one) surrounding these old machines.

**Comment by mebillica** [comment]
OK. github wont let me upload the file. says file type not supported. So I think I have it uploaded to my Google Drive. Here's the link.

https://drive.google.com/drive/folders/1Ic4q2AD9QrNfCmKSSI06L3VmGddkp6xw?usp=drive_link

Let me know if you got the f3d and stl ok. If not, I could email them to you.

Bill

**Comment by mebillica** [comment]
OK, I added the Build plate to Thingiverse. Here's the link:

https://www.thingiverse.com/thing:6648382

Thanks again!

Bill

**Comment by sigmondkukla** [comment]
These files are great and I'll drop them into the repository in a bit. Thanks so much for this contribution to keeping these machines alive!

**Comment by sigmondkukla** [comment]
Pull request #2 brings these changes onto the main branch. Let me know if there's anything else I can help with!
